spring:
  application:
    name: auth-api


server:
  port: 8100


jwt:
  secret: f5aec30ed11e9cd92f23f391ddc24ae931e08ac1352487d178e0547e50bd17d1
  refresh: 18fe93b955bf4861670b536214502d889288e3523f1ae02c6b28fae3b71f1bc3

management:
  health:
    status:
      order: DOWN, UP
  endpoint:
    jolokia:
      enabled: true
    metrics:
      enabled: true
    pause:
      enabled: true
    resume:
      enabled: true
    restart:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

eureka:
  instance:
    instance-id: core-api
    hostname: eureka-server
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@eureka-server:8761/eureka

nhncloud:
  keymanager:
    appkey: 2SxwmBzUfnqJaA2A
    redis:
      database: d7051ec1c8bd4322b1617c9d4a7a4620
      host: d105545a8b904e9ba27eab53d462c3a7
      port: 3c38f3964cdd4c0084bd21426cd6b93f
      password: abf22e4f003c42ae85c8d7e1ac668500
